Repository HexiumOS/Hexium, pull requests merged in 2025-04, with the labels that each got.

#15 Merge branch `dev` into `main`
  GNUmakefile
  README.md
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/src/fs/ramfs.rs
  kernel/src/lib.rs
  kernel/src/serial.rs
  kernel/src/writer.rs
Labels: bug, documentation, enhancement, good first issue

#22 Added a cooperative scheduler
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/src/devices/keyboard/mod.rs
  kernel/src/lib.rs
  kernel/src/task/executor.rs
  kernel/src/task/mod.rs
  kernel/src/utils/registers.rs
Labels: enhancement, good first issue

#24 Merge branch `dev` into `main`
  README.md
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/src/devices/keyboard/mod.rs
  kernel/src/devices/mod.rs
  kernel/src/drivers/pic.rs
  kernel/src/interrupts/idt.rs
  kernel/src/interrupts/mod.rs
  kernel/src/lib.rs
  kernel/src/log.rs
  kernel/src/main.rs
  kernel/src/task/executor.rs
  kernel/src/task/mod.rs
  kernel/src/utils/mod.rs
  kernel/src/utils/registers.rs
  kernel/src/writer.rs
Labels: bug, enhancement, good first issue

#27 Update makefile.yml
  .github/workflows/makefile.yml
Labels: bug, good first issue

#26 Basic custom #[no_std] test runner
  .github/workflows/makefile.yml
  .gitignore
  GNUmakefile
  kernel/.gitignore
  kernel/Cargo.toml
  kernel/GNUmakefile
  kernel/src/devices/keyboard/mod.rs
  kernel/src/fs/ramfs.rs
  kernel/src/interrupts/idt.rs
  kernel/src/lib.rs
  kernel/src/log.rs
  kernel/src/main.rs
  kernel/src/memory/mod.rs
  kernel/src/memory/paging.rs
  kernel/src/writer.rs
  kernel/tests/should_panic.rs
  kernel/tests/writer.rs
Labels: enhancement, good first issue
